version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:9000"
    volumes:
      - .:/var/www/html
    networks:
      - appnet
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE:
      MYSQL_USER: 
      MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD:
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "33061:3306"
    networks:
      - appnet
networks:
  appnet:
    driver: bridge
volumes:
  dbdata:
